[[new-features]]
== New & Noteworthy

[[new-features.3-0-0]]
=== What's new in Spring Vault 3.0

* Upgrade to Spring Framework 6 and Java 17 baseline
* Upgrade to AWS SDK 2.

=== What's new in Spring Vault 2.4

* Support for <<vault.authentication.userpass,Username/Password authentication>> for Username/Password, LDAP, Okta, and RADIUS authentication.
* Support of versioned Key/Value secrets engines for Vault repositories.
* <<vault.repositories.optimistic-locking,Optimistic locking support through Vault repositories using versioned Key/Value secrets engines>>.

[[new-features.2-3-0]]
=== What's new in Spring Vault 2.3

* Support for PEM-encoded certificates for keystore and truststore usage.
* `ReactiveVaultEndpointProvider` for non-blocking lookup of `VaultEndpoint`.
* `VaultKeyValueMetadataOperations` for Key-Value metadata interaction.
* Support for `transform` secrets engine (Enterprise Feature).
* Documentation of <<vault.core.secret-engines,how to use Vault secret backends>>.
* Login credentials for Kubernetes and PCF authentication are reloaded for each login attempt.
* `SecretLeaseContainer` publishes `SecretLeaseRotatedEvent` instead of `SecretLeaseExpiredEvent` and `SecretLeaseCreatedEvent` on successful secret rotation.
* `AbstractVaultConfiguration.threadPoolTaskScheduler()` bean type changed to `TaskSchedulerWrapper` instead of `ThreadPoolTaskScheduler`.
* Since 2.3.2: `GcpIamCredentialsAuthentication`

[[new-features.2-2-0]]
=== What's new in Spring Vault 2.2

* Support for Key-Value v2 (versioned secrets engine) secrets through `@VaultPropertySource`.
* SpEL support in `@Secret`.
* Add support for Jetty as reactive HttpClient.
* `LifecycleAwareSessionManager` and `ReactiveLifecycleAwareSessionManager` emit now ``AuthenticationEvent``s.
* <<vault.authentication.pcf>>.
* Deprecation of `AppIdAuthentication`.
Use `AppRoleAuthentication` instead as recommended by HashiCorp Vault.
* `CubbyholeAuthentication` and wrapped `AppRoleAuthentication` now use `sys/wrapping/unwrap` endpoints by default.
* Kotlin Coroutines support for `ReactiveVaultOperations`.

[[new-features.2-1-0]]
=== What's new in Spring Vault 2.1

* <<vault.authentication.gcpgce,GCP Compute>>, <<vault.authentication.gcpiam,GCP IAM>>, and <<vault.authentication.azuremsi, Azure>> authentication.
* Template API support for versioned and unversioned Key/Value secrets engines and for Vault wrapping operations.
* Support full pull mode in reactive AppRole authentication.
* Improved Exception hierarchy for Vault login failures.

[[new-features.2-0-0]]
=== What's new in Spring Vault 2.0

* Authentication steps DSL to <<vault.authentication.steps,compose authentication flows>>.
* <<vault.core.reactive.template,Reactive Vault client>> via `ReactiveVaultOperations`.
* <<vault.repositories,Vault repository support>> based on Spring Data KeyValue.
* Transit batch encrypt and decrypt support.
* Policy management for policies stored as JSON.
* Support CSR signing, certificate revocation and CRL retrieval.
* <<vault.authentication.kubernetes,Kubernetes authentication>>.
* RoleId/SecretId unwrapping for <<vault.authentication.approle,AppRole authentication>>.
* <<vault.misc.spring-security,Spring Security integration>> with transit secrets engine-based `BytesKeyGenerator` and `BytesEncryptor`.

[[new-features.1-1-0]]
=== What's new in Spring Vault 1.1.0

* <<vault.authentication.awsiam,AWS IAM authentication>>.
* Configuration of encryption/decryption versions for transit keys.
* Pull mode for <<vault.authentication.approle,AppRole authentication>>.
* Transit batch encrypt and decrypt support.
* TTL-based generic secret rotation.

[[new-features.1-0-0]]
=== What's new in Spring Vault 1.0

* Initial Vault support.

