name: Setup and Start Vault
description: 'Download and start a Vault server'

inputs:
  vault-version:
    description: 'Version of Vault to download'
    required: false

runs:
  using: composite
  steps:
    - name: Cache Vault
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          download
          vault
        key: ${{ runner.os }}-vault-${{ inputs.vault-version != '' && inputs.vault-version || 'default' }}

    - name: Install and Start Vault (explicit version)
      if: ${{ inputs.vault-version != '' }}
      shell: bash
      env:
        VAULT_OSS: ${{ inputs.vault-version }}
      run: src/test/bash/start.sh

    - name: Install and Start Vault (default version)
      if: ${{ inputs.vault-version == '' }}
      shell: bash
      run: src/test/bash/start.sh

