name: CI Build

on:
  push:
    branches: [ main, 4.0.x, 3.2.x, 3.1.x, 'issue/**' ]

permissions: read-all

jobs:
  build-java:
    name: Build project (${{ matrix.java-version }}${{ matrix.vault-version != '' && format(', Vault {0}', matrix.vault-version) || '' }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java-version: base
            vault-version: '1.21.5'
          - java-version: base
            vault-version: '2.0.0'
          - java-version: main
            vault-version: ''

    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@4.0.x
        with:
          java-version: '${{ matrix.java-version }}'
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'

      - name: Install and Start Vault
        uses: ./.github/actions/setup-vault
        with:
          vault-version: '${{ matrix.vault-version }}'

      - name: Build
        uses: spring-projects/spring-data-build/actions/maven-build@4.0.x
