name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main, 4.0.x, 3.2.x, 3.1.x, 'issue/**' ]

permissions: read-all

jobs:
  build-java:
    name: Build project (${{ matrix.java-version }}${{ matrix.vault-version != '' && format(', Vault {0}', matrix.vault-version) || '' }})
    runs-on: ${{ vars.ACTION_RUNNER || 'ubuntu-latest' }}

    strategy:
      matrix:
        include:
          - java-version: base
            vault-version: '1.21.4'
          - java-version: base
            vault-version: '2.0.0'
          - java-version: main
            vault-version: ''

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@4.0.x
        with:
          java-version: '${{ matrix.java-version }}'
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'

      - name: Install and Start Vault
        uses: ./.github/actions/setup-vault
        with:
          vault-version: '${{ matrix.vault-version }}'

      - name: Build
        uses: spring-projects/spring-data-build/actions/maven-build@4.0.x
        env:
          OSS_ARTIFACTORY_USR: '${{ secrets.ARTIFACTORY_USERNAME }}'
          OSS_ARTIFACTORY_PSW: '${{ secrets.ARTIFACTORY_PASSWORD }}'
          COMMERCIAL_ARTIFACTORY_USR: '${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}'
          COMMERCIAL_ARTIFACTORY_PSW: '${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}'
        with:
          settings-xml: '${{ vars.SETTINGS_XML }}'
